sudo: false
dist: trusty

matrix:
  include:
    - language: csharp
      mono: latest
      script: cd csharp && ./mono-build.sh

    - language: java
      script: cd java && ./gradlew build

    - language: cpp
      script: cd cpp && ./build.sh
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - ninja-build
            - clang-6.0

